let paintingList = [
	{
		"Index": "1",
		"Name": "Assunpink Winter Field",
		"Size": "11",
		"Year": "2015",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Winter Landscape",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "2",
		"Name": "Birds in Winter Field",
		"Size": "18",
		"Year": "2017",
		"Material": "Acrylic",
		"Cost unframed": "800",
		"Category": "Winter Landscape",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "3",
		"Name": "Empty Box Creek Winter Sunrise",
		"Size": "11",
		"Year": "2015",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Winter Landscape",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "4",
		"Name": "Empty Box Creek Winter Sunset",
		"Size": "11",
		"Year": "2015",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Winter Landscape",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "5",
		"Name": "Assunpink Winter Field",
		"Size": " Early Thaw",
		"Year": "11",
		"Material": "2016",
		"Cost unframed": "Acrylic",
		"Category": "400",
		"Comment ": "Winter Landscape",
		"Status": ""
	},
	{
		"Index": "6",
		"Name": "Snowy Field with Golden Trees",
		"Size": "11",
		"Year": "2016",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Winter Landscape",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "7",
		"Name": "Entrance to Field",
		"Size": "11",
		"Year": "2015",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Winter Landscape",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "8",
		"Name": "Winter Field with Fence",
		"Size": "11",
		"Year": "2015",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Winter Landscape",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "9",
		"Name": "Winter Farm Field",
		"Size": "11",
		"Year": "2015",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Winter Landscape",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "10",
		"Name": "Sunset on Snowy Fields",
		"Size": "11",
		"Year": "2015",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Winter Landscape",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "11",
		"Name": "Winter Farm ",
		"Size": "11",
		"Year": "2015",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Winter Landscape",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "12",
		"Name": "Winter Farm Field 2",
		"Size": "11",
		"Year": "2015",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Winter Landscape",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "13",
		"Name": "Winter Path to Field",
		"Size": "11",
		"Year": "2015",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Winter Landscape",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "14",
		"Name": "Winter Road",
		"Size": " Sunset",
		"Year": "11",
		"Material": "2015",
		"Cost unframed": "Acrylic",
		"Category": "400",
		"Comment ": "Winter Landscape",
		"Status": ""
	},
	{
		"Index": "15",
		"Name": "Aunt Tullie's Living Room ",
		"Size": "11",
		"Year": "2016",
		"Material": "Acrylic on paper",
		"Cost unframed": "400",
		"Category": "The Professor's Interiors",
		"Comment ": "The Professor always loved Aunt Tullie’s Living Room",
		"Status": " it felt like late spring there"
	},
	{
		"Index": "16",
		"Name": "Director's Office",
		"Size": "11",
		"Year": "2016",
		"Material": "Acrylic on paper",
		"Cost unframed": "400",
		"Category": "The Professor's Interiors",
		"Comment ": "The Professor always enjoyed having lunch with the Director in his office.",
		"Status": ""
	},
	{
		"Index": "17",
		"Name": "English Living Room",
		"Size": "14",
		"Year": "2016",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "The Professor's Interiors",
		"Comment ": "The Professor’s Grandmother’s Living Room in England always brought back fond memories of having High Tea with Grandmother and Aunt Tullie.",
		"Status": ""
	},
	{
		"Index": "18",
		"Name": "Favorite Restaurant in Italy",
		"Size": "11",
		"Year": "2016",
		"Material": "Acrylic on paper",
		"Cost unframed": "400",
		"Category": "The Professor's Interiors",
		"Comment ": "At the Professor’s favorite restaurant",
		"Status": " the food was not as memorable as the people"
	},
	{
		"Index": "19",
		"Name": "Harry's Enclosed Porch",
		"Size": "11",
		"Year": "2016",
		"Material": "Acrylic on paper",
		"Cost unframed": "400",
		"Category": "The Professor's Interiors",
		"Comment ": "The Professor and Harry",
		"Status": " sat in Harry’s enclosed porch on New Year’s Day and had lunch."
	},
	{
		"Index": "20",
		"Name": "Harry's Living Room",
		"Size": "14",
		"Year": "2016",
		"Material": "Acrylic on paper",
		"Cost unframed": "400",
		"Category": "The Professor's Interiors",
		"Comment ": "The family always spent New Year’s Eve at Harry",
		"Status": " the Professor's brother’s house. At midnight the tradition has been to wear the animal mask that they had got in Africa when they were children and tickling each other with peacock feathers. In years past their whole family would get involved"
	},
	{
		"Index": "21",
		"Name": "Lydia's for Thanksgiving",
		"Size": "22",
		"Year": "2017",
		"Material": "Acrylic on paper",
		"Cost unframed": "800",
		"Category": "The Professor's Interiors",
		"Comment ": "Lydia always had everyone over for Thanksgiving. During dinner there were people sitting in the hall",
		"Status": " and even on the stairs"
	},
	{
		"Index": "22",
		"Name": "Museum Court Yard",
		"Size": "11",
		"Year": "2017",
		"Material": "Acrylic on paper",
		"Cost unframed": "400",
		"Category": "The Professor's Interiors",
		"Comment ": "The museum court yard was the perfect place to do research. It was so nice that they let you take some of their archive material",
		"Status": " out there to study."
	},
	{
		"Index": "23",
		"Name": "The Professor's Front Hall",
		"Size": "11",
		"Year": "2015",
		"Material": "Acrylic on paper",
		"Cost unframed": "400",
		"Category": "The Professor's Interiors",
		"Comment ": "The professor’s grandfather clock was a gift from grandfather Smith",
		"Status": " it use to sit in the farm house in New Hampshire. When it chimed in the morning one almost expected to hear the rooster crow."
	},
	{
		"Index": "24",
		"Name": "The Professor's Study",
		"Size": "14",
		"Year": "2015",
		"Material": "Acrylic on paper",
		"Cost unframed": "400",
		"Category": "The Professor's Interiors",
		"Comment ": "The Geology Club met every second Wednesday at 5:00 here in the study. During that time the room was always packed with life and laughter.",
		"Status": ""
	},
	{
		"Index": "25",
		"Name": "The Professor's Unattached Porch",
		"Size": "14",
		"Year": "2017",
		"Material": "Acrylic on paper",
		"Cost unframed": "400",
		"Category": "The Professor's Interiors",
		"Comment ": "In the Spring the unattached porch was used at a study. Countless papers were revised at the table while kids and pets dashed in and out.",
		"Status": ""
	},
	{
		"Index": "26",
		"Name": "Tea Time at the Professor's",
		"Size": "14",
		"Year": "2015",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "The Professor's Interiors",
		"Comment ": "Tea Time at the Professor’ House several students came by every Thursday for a traditional Tea.",
		"Status": ""
	},
	{
		"Index": "27",
		"Name": "Salt Marsh",
		"Size": " Birds",
		"Year": "18",
		"Material": "2017",
		"Cost unframed": "Acrylic",
		"Category": "800",
		"Comment ": "Salt Marsh",
		"Status": ""
	},
	{
		"Index": "28",
		"Name": "Salt Marsh",
		"Size": " September",
		"Year": "11",
		"Material": "2016",
		"Cost unframed": "Acrylic",
		"Category": "400",
		"Comment ": "Salt Marsh",
		"Status": ""
	},
	{
		"Index": "29",
		"Name": "Salt Marsh",
		"Size": " November",
		"Year": "11",
		"Material": "2016",
		"Cost unframed": "Acrylic",
		"Category": "400",
		"Comment ": "Salt Marsh",
		"Status": ""
	},
	{
		"Index": "30",
		"Name": "Salt Marsh",
		"Size": " November 2",
		"Year": "11",
		"Material": "2016",
		"Cost unframed": "Acrylic",
		"Category": "400",
		"Comment ": "Salt Marsh",
		"Status": ""
	},
	{
		"Index": "31",
		"Name": "Salt Marsh",
		"Size": " November 3",
		"Year": "11",
		"Material": "2016",
		"Cost unframed": "Acrylic",
		"Category": "400",
		"Comment ": "Salt Marsh",
		"Status": ""
	},
	{
		"Index": "32",
		"Name": "Stone in the Middle of the Road",
		"Size": " Split in Two",
		"Year": "10",
		"Material": "2015",
		"Cost unframed": "Acrylic",
		"Category": "100",
		"Comment ": "Stone in the Middle of the Road",
		"Status": ""
	},
	{
		"Index": "33",
		"Name": "Stone in the Middle of the Road",
		"Size": " In the Woods",
		"Year": "10",
		"Material": "2015",
		"Cost unframed": "Acrylic",
		"Category": "100",
		"Comment ": "Stone in the Middle of the Road",
		"Status": ""
	},
	{
		"Index": "34",
		"Name": "Stone in the Middle of the Road",
		"Size": " From Both Sides",
		"Year": "10",
		"Material": "2015",
		"Cost unframed": "Acrylic",
		"Category": "100",
		"Comment ": "Stone in the Middle of the Road",
		"Status": ""
	},
	{
		"Index": "35",
		"Name": "Stone in the Middle of the Road",
		"Size": " As the Leaves Fall",
		"Year": "10",
		"Material": "2015",
		"Cost unframed": "Acrylic",
		"Category": "100",
		"Comment ": "Stone in the Middle of the Road",
		"Status": ""
	},
	{
		"Index": "36",
		"Name": "Stone in the Middle of the Road",
		"Size": " It Grows On You",
		"Year": "10",
		"Material": "2015",
		"Cost unframed": "Acrylic",
		"Category": "100",
		"Comment ": "Stone in the Middle of the Road",
		"Status": ""
	},
	{
		"Index": "37",
		"Name": "Stone in the Middle of the Road",
		"Size": " Could Not Stop Nature",
		"Year": "10",
		"Material": "2015",
		"Cost unframed": "Acrylic",
		"Category": "100",
		"Comment ": "Stone in the Middle of the Road",
		"Status": ""
	},
	{
		"Index": "38",
		"Name": "Stone in the Middle of the Road",
		"Size": " Diverts the Path",
		"Year": "10",
		"Material": "2015",
		"Cost unframed": "Acrylic",
		"Category": "100",
		"Comment ": "Stone in the Middle of the Road",
		"Status": ""
	},
	{
		"Index": "39",
		"Name": "Stone in the Middle of the Road",
		"Size": " As a Bridge",
		"Year": "10",
		"Material": "2015",
		"Cost unframed": "Acrylic",
		"Category": "100",
		"Comment ": "Stone in the Middle of the Road",
		"Status": ""
	},
	{
		"Index": "40",
		"Name": "Stone in the Middle of the Road",
		"Size": " Split in Two",
		"Year": " a Different View",
		"Material": "10",
		"Cost unframed": "2015",
		"Category": "Acrylic",
		"Comment ": "100",
		"Status": "Stone in the Middle of the Road"
	},
	{
		"Index": "41",
		"Name": "Stone in the Middle of the Road",
		"Size": " It is the Small Things That Make a Difference ",
		"Year": "10",
		"Material": "2015",
		"Cost unframed": "Acrylic",
		"Category": "100",
		"Comment ": "Stone in the Middle of the Road",
		"Status": ""
	},
	{
		"Index": "42",
		"Name": "A R Wallace",
		"Size": " Listening to a Tuba Player",
		"Year": "11",
		"Material": "2006 - 2008",
		"Cost unframed": "Pencil on paper",
		"Category": "50",
		"Comment ": "Drawing",
		"Status": ""
	},
	{
		"Index": "43",
		"Name": "Advise for the Queen",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "44",
		"Name": "Amalia's Pearls",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "45",
		"Name": "Cat's Spirit",
		"Size": "11",
		"Year": "2006 - 2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "46",
		"Name": "Cezanne and Hippos",
		"Size": " Near Caravan",
		"Year": "11",
		"Material": "2006 - 2008",
		"Cost unframed": "Pencil on paper",
		"Category": "50",
		"Comment ": "Drawing",
		"Status": ""
	},
	{
		"Index": "47",
		"Name": "Children",
		"Size": " Gloves",
		"Year": " and Animals",
		"Material": "11",
		"Cost unframed": "2006-2008",
		"Category": "Pencil on paper",
		"Comment ": "50",
		"Status": "Drawing"
	},
	{
		"Index": "48",
		"Name": "Choosing a Tea Pot",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "49",
		"Name": "Contemplating the Universe",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "50",
		"Name": "Desert Nights",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "51",
		"Name": "Ellis Island",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "52",
		"Name": "Farmers",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "53",
		"Name": "Feeding the Animals",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "54",
		"Name": "Fishing for God",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "55",
		"Name": "Flight",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "56",
		"Name": "Frog Legs",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "57",
		"Name": "Full Moon",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "58",
		"Name": "Head of a Girl",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "59",
		"Name": "Horse Races on the Steppes",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "60",
		"Name": "In Flight",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "61",
		"Name": "In the Jungle",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "62",
		"Name": "In the Tent",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "63",
		"Name": "Island Archeology",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "64",
		"Name": "It is Spring",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "65",
		"Name": "Italian Sunglasses",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "66",
		"Name": "Japenese Physicist",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "67",
		"Name": "Judy's Grand Daughter",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "68",
		"Name": "Listening",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "69",
		"Name": "Market Place",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "70",
		"Name": "Midnight in the Garden of Art and Science",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "71",
		"Name": "Naptime",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "72",
		"Name": "Nightmare at the Bayou",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "73",
		"Name": "Observing Closely",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "74",
		"Name": "Ponds Edge",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "75",
		"Name": "Questions",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "76",
		"Name": "Recital",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "77",
		"Name": "Resting",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "78",
		"Name": "School Children",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "79",
		"Name": "Seated Model",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "80",
		"Name": "Silk Road",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "81",
		"Name": "St John's Pond",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "82",
		"Name": "Staying a Float",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "83",
		"Name": "The Armchair Traveler",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "84",
		"Name": "The Cosmic Car Therory",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "85",
		"Name": "The Dance",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "86",
		"Name": "The Hall",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "87",
		"Name": "The Library",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "88",
		"Name": "The Parade",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "89",
		"Name": "The Road to the Market",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "90",
		"Name": "The Tall Tale",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "91",
		"Name": "The Waiting Room",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "92",
		"Name": "They Could Not Be Caught",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "93",
		"Name": "They Talked of Religion",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "94",
		"Name": "They Thought About the Day Over Coffee",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "95",
		"Name": "They Waited",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "96",
		"Name": "Travel Picture",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "97",
		"Name": "Under the Bridge",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "98",
		"Name": "Under the Island",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Pencil on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "99",
		"Name": "While he Sat his Thoughts Wondered",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "100",
		"Name": "Wrestlers",
		"Size": "11",
		"Year": "2006-2008",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Drawing",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "101",
		"Name": "Chet 1",
		"Size": "8",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "100",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "102",
		"Name": "Chet 2",
		"Size": "8",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "100",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "103",
		"Name": "Chet 3",
		"Size": "8",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "100",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "104",
		"Name": "Cold River Field",
		"Size": "8",
		"Year": "2008",
		"Material": "Acrylic on paper",
		"Cost unframed": "100",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "105",
		"Name": "Cold River Library",
		"Size": " Night",
		"Year": "11",
		"Material": "2010",
		"Cost unframed": "Pastels",
		"Category": "400",
		"Comment ": "Cold River Camp",
		"Status": ""
	},
	{
		"Index": "106",
		"Name": "Cold River Porch",
		"Size": "11",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "107",
		"Name": "Cold River Cabin",
		"Size": "11",
		"Year": "2013",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "108",
		"Name": "Cold River Library 1",
		"Size": "11",
		"Year": "2010",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "109",
		"Name": "Cold River Library 2",
		"Size": "11",
		"Year": "2010",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "110",
		"Name": "Cold River Porch 2",
		"Size": "11",
		"Year": "2014",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "111",
		"Name": "Cold River Vantican City",
		"Size": "11",
		"Year": "2014",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": "Sold"
	},
	{
		"Index": "112",
		"Name": "Path to Emerald Pool",
		"Size": "18",
		"Year": "2016",
		"Material": "Acrylic",
		"Cost unframed": "800",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "113",
		"Name": "Tea House at Cold River",
		"Size": "11",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "114",
		"Name": "Spring Haven Interior",
		"Size": "11",
		"Year": "2013",
		"Material": "Watercolor on paper",
		"Cost unframed": "sold",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": "sold"
	},
	{
		"Index": "115",
		"Name": "Spring Haven Exterior",
		"Size": "11",
		"Year": "2013",
		"Material": "Watercolor on paper",
		"Cost unframed": "sold",
		"Category": "Cold River Camp",
		"Comment ": "",
		"Status": "sold"
	},
	{
		"Index": "116",
		"Name": "Bears",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "117",
		"Name": "Bommer",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "sold",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "118",
		"Name": "Bommer 2",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "sold",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "119",
		"Name": "Cat ",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "120",
		"Name": "Cats",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "121",
		"Name": "Chipmunk",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "122",
		"Name": "Chipmunk 2",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "123",
		"Name": "Deer at Sunset",
		"Size": "10",
		"Year": "2011",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "124",
		"Name": "Deer in Woods",
		"Size": "10",
		"Year": "2012",
		"Material": "Pastels",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "125",
		"Name": "Deer",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "126",
		"Name": "Dogs",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "127",
		"Name": "Fox",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "128",
		"Name": "Fox 2",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "129",
		"Name": "Lily",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "sold",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "130",
		"Name": "Rabbit",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "131",
		"Name": "Rabbit 2",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "132",
		"Name": "Rabbit 2a",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "133",
		"Name": "Rabbit 3",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "134",
		"Name": "Raccoon",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "135",
		"Name": "Raccoon 2",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "136",
		"Name": "Spirit of a Cat",
		"Size": "10",
		"Year": "2001",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "137",
		"Name": "Squirrel",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "138",
		"Name": "Stag",
		"Size": "10",
		"Year": "2011",
		"Material": "Acrylic",
		"Cost unframed": "50",
		"Category": "Animals",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "139",
		"Name": "7 13 09",
		"Size": "10",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "140",
		"Name": "7 13 09 2",
		"Size": "10",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "141",
		"Name": "7 13 09 3",
		"Size": "10",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "142",
		"Name": "7 16 09",
		"Size": "10",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "143",
		"Name": "7 16 09 Evening",
		"Size": "10",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "144",
		"Name": "7 23 09",
		"Size": "10",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "145",
		"Name": "7 24 09 Morning",
		"Size": "10",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "146",
		"Name": "7 24 09 Sunset",
		"Size": "10",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "147",
		"Name": "School Doors",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "148",
		"Name": "Sea Isle City Sunrise",
		"Size": "11",
		"Year": "2015",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "149",
		"Name": "Sunrise/ Sunset 2008 i",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "150",
		"Name": "Sunrise/ Sunset 2008 ii",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "151",
		"Name": "Sunrise/ Sunset 2008 iii",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "152",
		"Name": "Sunrise/ Sunset 2008 iv",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "153",
		"Name": "Sunrise/ Sunset 2008 ix",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "154",
		"Name": "Sunrise/ Sunset 2008 v",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "155",
		"Name": "Sunrise/ Sunset 2008 vi",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "156",
		"Name": "Sunrise/ Sunset 2008 vii",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "157",
		"Name": "Sunrise/ Sunset 2008 viii",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "158",
		"Name": "Sunrise/ Sunset 2008 x",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "159",
		"Name": "Sunrise/Sunset 2008 xi",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "160",
		"Name": "Sunrise/ Sunset 2008 xii",
		"Size": "10",
		"Year": "2008",
		"Material": "Watercolor on paper",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "161",
		"Name": "C1",
		"Size": "11",
		"Year": "2016",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "162",
		"Name": "Clay Print 2",
		"Size": "11",
		"Year": "2008",
		"Material": "Clay",
		"Cost unframed": "50",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "163",
		"Name": "Clay Print 3",
		"Size": "11",
		"Year": "2008",
		"Material": "Clay",
		"Cost unframed": "50",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "164",
		"Name": "Clay Print with Felting",
		"Size": "11",
		"Year": "2008",
		"Material": "Clay and Wool",
		"Cost unframed": "50",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "165",
		"Name": "Day of the Dead Freda Portrait",
		"Size": "8",
		"Year": "2016",
		"Material": "Acrylic",
		"Cost unframed": "150",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "166",
		"Name": "Day of the Dead",
		"Size": "8",
		"Year": "2008",
		"Material": "Oil",
		"Cost unframed": "150",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "167",
		"Name": "Fairies Sleeping",
		"Size": "11",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "168",
		"Name": "Illuminated Writing 2",
		"Size": "8",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "169",
		"Name": "Illuminated Writing 3",
		"Size": "8",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "170",
		"Name": "Illuminated Writing 4",
		"Size": "8",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "171",
		"Name": "Illuminated Writing 5",
		"Size": "8",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "172",
		"Name": "Illuminated Writing 6",
		"Size": "8",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "173",
		"Name": "Post Card Intersection",
		"Size": "5",
		"Year": "2010",
		"Material": "Mixmedia",
		"Cost unframed": "sold",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "174",
		"Name": "Natures Bath",
		"Size": "18",
		"Year": "2009",
		"Material": "Pastels",
		"Cost unframed": "800",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "175",
		"Name": "The Source",
		"Size": "11",
		"Year": "2015",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Abstract and Fantasy",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "176",
		"Name": "Beach Scene 2",
		"Size": "11",
		"Year": "2010",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Beach",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "177",
		"Name": "Belmar Beach",
		"Size": "11",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Beach",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "178",
		"Name": "Boats",
		"Size": "11",
		"Year": "1975",
		"Material": "Graphite",
		"Cost unframed": "50",
		"Category": "Beach",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "179",
		"Name": "Island State Park Beach",
		"Size": "11",
		"Year": "2010",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Beach",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "180",
		"Name": "Mystic Connecticut",
		"Size": " Boats",
		"Year": "11",
		"Material": "1999",
		"Cost unframed": "Pastels",
		"Category": "400",
		"Comment ": "Beach",
		"Status": ""
	},
	{
		"Index": "181",
		"Name": "Mystic Connecticut Inlet",
		"Size": "11",
		"Year": "1999",
		"Material": "Pastels",
		"Cost unframed": "400",
		"Category": "Beach",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "182",
		"Name": "Ocean City Houses",
		"Size": "11",
		"Year": "2014",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Beach",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "183",
		"Name": "Ocean City Sunrise",
		"Size": "11",
		"Year": "2014",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Beach",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "184",
		"Name": "Sunbathers",
		"Size": "11",
		"Year": "2009",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Beach",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "185",
		"Name": "Bone",
		"Size": "11",
		"Year": "1977",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "186",
		"Name": "Bone Series 13",
		"Size": "11",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "187",
		"Name": "Bone Series 14",
		"Size": "11",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "188",
		"Name": "Bone Series 15",
		"Size": "11",
		"Year": "1977",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "189",
		"Name": "Bone Series 16",
		"Size": "11",
		"Year": "1977",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "190",
		"Name": "Bone Series 17",
		"Size": "11",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "191",
		"Name": "Bone Series 18",
		"Size": "11",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "192",
		"Name": "Bone Series 19",
		"Size": "11",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "193",
		"Name": "Bone Series xx",
		"Size": "11",
		"Year": "1977",
		"Material": "Ink on paper",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "194",
		"Name": "Bone Series xxi",
		"Size": "11",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "195",
		"Name": "Figure Study 1",
		"Size": "11",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "196",
		"Name": "Figure Study 2",
		"Size": "11",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "197",
		"Name": "Figure Study 3",
		"Size": "11",
		"Year": "1977",
		"Material": "Mixmedia",
		"Cost unframed": "50",
		"Category": "Bone",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "198",
		"Name": "Assunpink Fall Weeds",
		"Size": "11",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "199",
		"Name": "Assunpink Fall Summer Fields",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "200",
		"Name": "Assunpink Stone Tavern Lake",
		"Size": "18",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "800",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "201",
		"Name": "Back Pasture",
		"Size": " San Antonio",
		"Year": "11",
		"Material": "",
		"Cost unframed": "Acrylic",
		"Category": "800",
		"Comment ": "Field and Lakes",
		"Status": ""
	},
	{
		"Index": "202",
		"Name": "Brown Field",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "203",
		"Name": "Camp Fire",
		"Size": "10",
		"Year": "",
		"Material": "acrylic",
		"Cost unframed": "100",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "204",
		"Name": "Camp Fire 2",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "205",
		"Name": "Camp Fire 3",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "206",
		"Name": "Clay Print of leaves",
		"Size": "11",
		"Year": "",
		"Material": "Clay",
		"Cost unframed": "150",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "207",
		"Name": "Delaware Water Gap",
		"Size": " Fall Field",
		"Year": "11",
		"Material": "",
		"Cost unframed": "Watercolor on paper",
		"Category": "400",
		"Comment ": "Field and Lakes",
		"Status": ""
	},
	{
		"Index": "208",
		"Name": "Dorsey's Fishing Place",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "sold",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "209",
		"Name": "Early Summer Corn Field",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "210",
		"Name": "Early Fall Meadow",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "211",
		"Name": "Field in Early Morning Light",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "212",
		"Name": "Haddonfield Bridge",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "213",
		"Name": "San Antonio Aqueduct",
		"Size": "24",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "800",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "214",
		"Name": "Millstone Watershed Pond",
		"Size": "7",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "90",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "215",
		"Name": "NJ Farm House",
		"Size": "7",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "90",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "216",
		"Name": "NJ Farm ",
		"Size": "7",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "90",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "217",
		"Name": "St Mary's Co. Barn",
		"Size": "8",
		"Year": "1976",
		"Material": "Watercolor on paper",
		"Cost unframed": "100",
		"Category": "Field and Lakes",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "218",
		"Name": "Terhune Orchard",
		"Size": " Apple Trees",
		"Year": "11",
		"Material": "",
		"Cost unframed": "Acrylic",
		"Category": "400",
		"Comment ": "Field and Lakes",
		"Status": ""
	},
	{
		"Index": "219",
		"Name": "Terhune Orchard",
		"Size": " Cherries",
		"Year": "11",
		"Material": "",
		"Cost unframed": "Acrylic",
		"Category": "400",
		"Comment ": "Field and Lakes",
		"Status": ""
	},
	{
		"Index": "220",
		"Name": "A Walk in the Woods",
		"Size": "11",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "221",
		"Name": "Delaware Water Gap",
		"Size": " Stream",
		"Year": "18",
		"Material": "",
		"Cost unframed": "Acrylic",
		"Category": "800",
		"Comment ": "Forest Path",
		"Status": ""
	},
	{
		"Index": "222",
		"Name": "Fall Mountain Stream",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "223",
		"Name": "Forest Bathing",
		"Size": "11",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "224",
		"Name": "Grid Landscape",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "225",
		"Name": "Hiking in the Mountains",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "300",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "226",
		"Name": "Mountain Fall",
		"Size": "8",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "300",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "227",
		"Name": "My November Guest",
		"Size": "8",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "300",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "228",
		"Name": "NJ Stream",
		"Size": "11",
		"Year": "2000",
		"Material": "Pastels",
		"Cost unframed": "300",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "229",
		"Name": "NJ Woods",
		"Size": "11",
		"Year": "2001",
		"Material": "Pastels",
		"Cost unframed": "300",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "230",
		"Name": "North NJ Park Bridge",
		"Size": "11",
		"Year": "2000",
		"Material": "Pastels",
		"Cost unframed": "300",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "231",
		"Name": "Printed Landscape",
		"Size": "11",
		"Year": "",
		"Material": "Print",
		"Cost unframed": "400",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "232",
		"Name": "River Reflections",
		"Size": "11",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "400",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "233",
		"Name": "Roosevelt Woods",
		"Size": " Late Afternoon",
		"Year": "18",
		"Material": "",
		"Cost unframed": "Acrylic",
		"Category": "800",
		"Comment ": "Forest Path",
		"Status": ""
	},
	{
		"Index": "234",
		"Name": "Roosevelt Woods",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "235",
		"Name": "Rutgers Garden Woods",
		"Size": "8",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "300",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "236",
		"Name": "Summer Greens",
		"Size": "11",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "400",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "237",
		"Name": "Sunrise Mountain",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "238",
		"Name": "The Encounter in the Woods",
		"Size": "11",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "400",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "239",
		"Name": "Tillman Ravine Fall Stream",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "240",
		"Name": "Tillman Ravine Fall Stream 2",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "241",
		"Name": "Tillman Ravine Fall Stream 3",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "242",
		"Name": "Tillman Ravine Fall Stream 4",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "243",
		"Name": "Tillman Ravine Fall Stream 5",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "244",
		"Name": "Two Roads Divided in a Yellow Woods",
		"Size": "18",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "800",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "245",
		"Name": "Winter Woods",
		"Size": "8",
		"Year": "",
		"Material": "Mixmedia",
		"Cost unframed": "100",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "246",
		"Name": "Woodland Path",
		"Size": "11",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "247",
		"Name": "Delaware Water Gap Stream 2",
		"Size": "18",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "800",
		"Category": "Forest Path",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "248",
		"Name": "Sunset Pikes Peak",
		"Size": "11",
		"Year": "",
		"Material": "Colored Pencil",
		"Cost unframed": "50",
		"Category": "Sunrise/Sunset Series",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "249",
		"Name": "7 16 09",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "300",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "250",
		"Name": "Brookside Path",
		"Size": "7",
		"Year": "",
		"Material": "pastels",
		"Cost unframed": "100",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "251",
		"Name": "Garden Path",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "300",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "252",
		"Name": "Garden Tour Painting",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "400",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "253",
		"Name": "Kirk and Susan's Garden",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "sold",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "254",
		"Name": "Kirk and Susan's Garden 2",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "sold",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "255",
		"Name": "Kirk and Susan's Garden 3",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "sold",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "256",
		"Name": "Kirk and Susan's Garde 4 ",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "sold",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "257",
		"Name": "Kirk and Susan's Garden 5 ",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "sold",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "258",
		"Name": "Kirk and Susan's Garden 6 ",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on paper",
		"Cost unframed": "sold",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "259",
		"Name": "Kuser Mansion ",
		"Size": "11",
		"Year": "",
		"Material": "Acylic",
		"Cost unframed": "",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "260",
		"Name": "Kuser Mansion 2 ",
		"Size": "11",
		"Year": "",
		"Material": "Acylic",
		"Cost unframed": "",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "261",
		"Name": "My Garden",
		"Size": "11",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "262",
		"Name": "Pleasant Run Garden",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "400",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "263",
		"Name": "Rutgers Garden Early Spring Path",
		"Size": "12",
		"Year": "2018",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "264",
		"Name": "Rutgers Garden Early Spring",
		"Size": "",
		"Year": "2018",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "265",
		"Name": "Sayers Garden Fountain",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "400",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "266",
		"Name": "Sharp's Garden Bird Bath",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "400",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "267",
		"Name": "Sharp's Garden Notes",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "400",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "268",
		"Name": "Sharp's Garden Patio",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "400",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "269",
		"Name": "Sharp's Pink Lawn Chairs",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "400",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "270",
		"Name": "Spring Brookside",
		"Size": "22",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "800",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "271",
		"Name": "Brookside Tea House",
		"Size": "25",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "800",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "272",
		"Name": "Thompson Neel House",
		"Size": "11",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "273",
		"Name": "Walford Porch",
		"Size": "8",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "300",
		"Category": "Gardens",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "274",
		"Name": "Fighting Fires",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "300",
		"Category": "Illustration",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "275",
		"Name": "Peguins",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "300",
		"Category": "Illustration",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "276",
		"Name": "Pony Express",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "300",
		"Category": "Illustration",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "277",
		"Name": "Clowns",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "300",
		"Category": "Illustration",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "278",
		"Name": "Sleepy and Doc at a Birthday Party",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "300",
		"Category": "Illustration",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "279",
		"Name": "Allentown Street Scene",
		"Size": "8",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "Sold",
		"Category": "NJ Town and Shops",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "280",
		"Name": "Bruno's Bicycles",
		"Size": " Bruno at Front Counter",
		"Year": "11",
		"Material": "",
		"Cost unframed": "Acrylic",
		"Category": "400",
		"Comment ": "NJ Town and Shops",
		"Status": ""
	},
	{
		"Index": "281",
		"Name": "Bruno's Bicycles",
		"Size": " Front Window",
		"Year": "11",
		"Material": "",
		"Cost unframed": "Acrylic",
		"Category": "400",
		"Comment ": "NJ Town and Shops",
		"Status": ""
	},
	{
		"Index": "282",
		"Name": "Bruno's Bicycles",
		"Size": " One Sweet Ride Candy Counter",
		"Year": "11",
		"Material": "",
		"Cost unframed": "Acrylic",
		"Category": "400",
		"Comment ": "NJ Town and Shops",
		"Status": ""
	},
	{
		"Index": "283",
		"Name": "House on Virginia Avenue",
		"Size": "11",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "NJ Town and Shops",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "284",
		"Name": "Laurita Winery 5",
		"Size": "11",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "NJ Town and Shops",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "285",
		"Name": "Mill Pond Shop",
		"Size": "8",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "sold",
		"Category": "NJ Town and Shops",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "286",
		"Name": "Interior with Two Dogs",
		"Size": "8",
		"Year": "",
		"Material": "Oil Pastels",
		"Cost unframed": "300",
		"Category": "Other Interiors",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "287",
		"Name": "My Grandmother's Dining Room",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "",
		"Category": "Other Interiors",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "288",
		"Name": "My Grandmother's Living Room",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "",
		"Category": "Other Interiors",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "289",
		"Name": "Orange Living Room",
		"Size": "",
		"Year": "",
		"Material": "Oil ",
		"Cost unframed": "",
		"Category": "Other Interiors",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "290",
		"Name": "Red Chairs in Dining Room",
		"Size": "",
		"Year": "",
		"Material": "Oil Pastels",
		"Cost unframed": "",
		"Category": "Other Interiors",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "291",
		"Name": "Yellow and Red Room",
		"Size": "",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "",
		"Category": "Other Interiors",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "292",
		"Name": "Yellow Living Room",
		"Size": "",
		"Year": "",
		"Material": "Oil",
		"Cost unframed": "",
		"Category": "Other Interiors",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "293",
		"Name": "A Childhood Picture of My Mom",
		"Size": "11",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "294",
		"Name": "Belly Dancer",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "295",
		"Name": "Belly Dancers",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "296",
		"Name": "Ben 2",
		"Size": "8",
		"Year": "",
		"Material": "Pencil",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "297",
		"Name": "Ben 3",
		"Size": "8",
		"Year": "",
		"Material": "Pencil",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "298",
		"Name": "Ben and Mike 4",
		"Size": "8",
		"Year": "",
		"Material": "Pencil",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "299",
		"Name": "Bev",
		"Size": "8",
		"Year": "",
		"Material": "Pencil",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "300",
		"Name": "Bumble Bee 1",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "301",
		"Name": "Bumble Bee 2",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "302",
		"Name": "Dad Dancing 1",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "sold",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "303",
		"Name": "Dad Dancing 2",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "sold",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "304",
		"Name": "Dad Dancing 3",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "sold",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "305",
		"Name": "Dad",
		"Size": "",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "306",
		"Name": "Double Self Portait",
		"Size": "",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "307",
		"Name": "Elaine",
		"Size": "8",
		"Year": "",
		"Material": "Pencil",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "308",
		"Name": "Fishing with Grand Dad 1",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "sold",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "309",
		"Name": "Fishing with Grand Dad 2",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "sold",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "310",
		"Name": "Fishing with Grand Dad 3",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "sold",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "311",
		"Name": "Grandmother and Her Sisters ",
		"Size": "11",
		"Year": "",
		"Material": "Pencil",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "312",
		"Name": "Grandmother and Her Sisters 1",
		"Size": "11",
		"Year": "",
		"Material": "Pencil",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "313",
		"Name": "Grandmother and Her Sisters 3",
		"Size": "11",
		"Year": "",
		"Material": "Pencil",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "314",
		"Name": "Grandmother and Her Sisters 6",
		"Size": "11",
		"Year": "",
		"Material": "Pencil",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "315",
		"Name": "Grandmother and Her Sisters 2",
		"Size": "11",
		"Year": "",
		"Material": "Pencil",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "316",
		"Name": "Mexican Folk Dance",
		"Size": "11",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "317",
		"Name": "Mike in Cowboy with Horse Costume",
		"Size": "8",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "318",
		"Name": "Mom and Dad Cutting the Rug",
		"Size": "",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "sold",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "319",
		"Name": "Mom ",
		"Size": "",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "320",
		"Name": "Paul on the Mission Trail",
		"Size": "",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "sold",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "321",
		"Name": "Ralph",
		"Size": "11",
		"Year": "",
		"Material": "Colored Pencil",
		"Cost unframed": "",
		"Category": "People",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "322",
		"Name": "Grow Beyond the Drip Line",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "$100.00",
		"Category": "Roots",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "323",
		"Name": "Growth Rings",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Roots",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "324",
		"Name": "Putting Down Roots",
		"Size": "20",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "400",
		"Category": "Roots",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "325",
		"Name": "Uprooted 1",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Roots",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "326",
		"Name": "Uprooted 2",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Roots",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "327",
		"Name": "Uprooted 3",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Roots",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "328",
		"Name": "Uprooted 4",
		"Size": "10",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "100",
		"Category": "Roots",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "329",
		"Name": "Botanical Still Life",
		"Size": "",
		"Year": "",
		"Material": "Acrylic",
		"Cost unframed": "",
		"Category": "Still Life",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "330",
		"Name": "Brown Chair",
		"Size": "8",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "100",
		"Category": "Still Life",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "331",
		"Name": "Chair with Blue Background",
		"Size": "8",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "100",
		"Category": "Still Life",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "332",
		"Name": "Chair with Pink Background",
		"Size": "8",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "100",
		"Category": "Still Life",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "333",
		"Name": "Still Life",
		"Size": "8",
		"Year": "",
		"Material": "Watercolor on Paper",
		"Cost unframed": "50",
		"Category": "Still Life",
		"Comment ": "",
		"Status": ""
	},
	{
		"Index": "334",
		"Name": "Whisp Broom Ladies",
		"Size": "18",
		"Year": "",
		"Material": "Pastels",
		"Cost unframed": "",
		"Category": "Still Life",
		"Comment ": "",
		"Status": ""
	}
]
